/**
 * Eigencompute TEE Proof Types
 * 
 * Defines the structure for cryptographic proofs generated by Eigencompute's
 * Trusted Execution Environment when processing documents with Claude Sonnet 4.5
 */

/**
 * TEE Attestation from Eigencompute
 * Cryptographic proof that the AI extraction happened in a secure enclave
 */
export interface TEEAttestation {
  /** Unique attestation ID from Eigencompute */
  attestationId: string;
  /** TEE platform (e.g., "SGX", "NITRO") */
  platform: string;
  /** Enclave measurements for verification */
  measurements: {
    mrenclave?: string; // SGX enclave measurement
    mrsigner?: string;  // SGX signer measurement
    pcr?: string[];     // Nitro PCR values
  };
  /** Attestation signature */
  signature: string;
  /** Timestamp of attestation */
  timestamp: string;
  /** Additional metadata */
  metadata?: Record<string, unknown>;
}

/**
 * Eigencompute Proof for a single extraction
 * Links the TEE attestation to the actual extraction result
 */
export interface EigencomputeProof {
  /** Unique proof ID from Eigencompute */
  proofId: string;
  /** SHA-256 hash of the original document */
  docHash: string;
  /** TEE attestation data */
  attestation: TEEAttestation;
  /** Claude API request details */
  apiRequest: {
    model: string;
    timestamp: string;
    requestHash: string; // Hash of the request payload
  };
  /** Claude API response details */
  apiResponse: {
    responseHash: string; // Hash of the response payload
    timestamp: string;
  };
  /** Merkle root of all field proofs (for batch verification) */
  merkleRoot?: string;
  /** Proof creation timestamp */
  createdAt: string;
}

/**
 * Field-level proof linking extraction to source
 * Combines Eigencompute's TEE proof with field-specific data
 */
export interface FieldProof {
  /** Field name (e.g., "total", "merchant", "date") */
  field: string;
  /** Extracted value */
  value: unknown;
  /** Exact source text from document */
  sourceText: string;
  /** Bounding box coordinates (from OCR alignment) */
  boundingBox?: BoundingBox;
  /** OCR words that match this field */
  ocrWords?: string[];
  /** Combined confidence score (0-1) */
  confidence: number;
  /** AI model used for extraction */
  model: string;
  /** Hash of this specific field proof */
  proofHash: string;
  /** Reference to parent Eigencompute proof */
  eigencomputeProofId: string;
  /** Timestamp of extraction */
  timestamp: string;
}

/**
 * Bounding box coordinates in pixels
 */
export interface BoundingBox {
  x: number;
  y: number;
  width: number;
  height: number;
}

/**
 * Complete document proof structure
 * Combines document hash, all field proofs, and Eigencompute attestation
 */
export interface DocumentProof {
  /** Document ID */
  docId: string;
  /** SHA-256 hash of document bytes */
  docHash: string;
  /** Document type classification */
  documentType: 'receipt' | 'invoice' | 'contract';
  /** All field-level proofs */
  fields: FieldProof[];
  /** Eigencompute TEE proof */
  eigencomputeProof: EigencomputeProof;
  /** Merkle root of all field proof hashes */
  merkleRoot: string;
  /** Overall confidence score */
  overallConfidence: number;
  /** Total processing time in ms */
  processingTime: number;
  /** Creation timestamp */
  createdAt: string;
}

/**
 * Verification result when re-uploading a document
 */
export interface VerificationResult {
  /** Whether verification succeeded */
  verified: boolean;
  /** Hash of re-uploaded document */
  newHash: string;
  /** Original stored hash */
  originalHash: string;
  /** Whether hashes match */
  hashMatch: boolean;
  /** Human-readable message */
  message: string;
  /** Individual field verification results */
  fieldVerifications?: Array<{
    field: string;
    verified: boolean;
    reason?: string;
  }>;
  /** Verification timestamp */
  timestamp: string;
}

/**
 * Eigencompute API configuration
 */
export interface EigencomputeConfig {
  apiKey: string;
  endpoint: string;
  teeEnabled: boolean;
  timeout?: number;
  retries?: number;
}

/**
 * Request to Eigencompute for document processing
 */
export interface EigencomputeProcessRequest {
  /** Document image as base64 */
  imageBase64: string;
  /** Document hash for integrity */
  docHash: string;
  /** Claude model to use */
  model: string;
  /** Extraction prompt */
  prompt: string;
  /** Additional metadata */
  metadata?: Record<string, unknown>;
}

/**
 * Response from Eigencompute after processing
 */
export interface EigencomputeProcessResponse {
  /** Unique proof ID */
  proofId: string;
  /** TEE attestation data */
  attestation: TEEAttestation;
  /** Extracted data from Claude */
  extractedData: {
    documentType: string;
    fields: Array<{
      field: string;
      value: unknown;
      sourceText: string;
      confidence: number;
    }>;
  };
  /** Processing metadata */
  metadata: {
    processingTime: number;
    model: string;
    timestamp: string;
  };
}

